### ISSUE TITLE
Validation for page range?

### ISSUE THREAD

**Issue by pythonissam** [pbrisbin/yesod-paginator#29] opened 2018-08-06 07:51 UTC
Currently, three's no validation for param `p`. For example, using [this code](https://github.com/pbrisbin/yesod-paginator/blob/master/example/Main.hs), http://localhost:3000/?p=-1 shows http://localhost:3000/?p=-1 and http://localhost:3000/?p=2000 shows page links which don't exist.

Are there any plan to fix these issues?

**Comment by pbrisbin** [comment] 2018-08-06 15:57
> http://localhost:3000/?p=-1 shows http://localhost:3000/?p=-1

I can't reproduce this. I get a 500 with `arithmetic underflow`, which isn't great, but is what I would expect and I'm considering it acceptable for now.

Replacing `readIntegral` with `readMay` [here](https://github.com/pbrisbin/yesod-paginator/blob/master/src/Yesod/Paginator/Paginate.hs#L92) is probably a smart thing to do, as it would replace that 500 with a defaulting to `1`. Unfortunately the URL would still say `-1` so that's a bit weird.

> http://localhost:3000/?p=2000 shows page links which don't exist.

I might refer to them as "links to empty pages." And I also consider this behavior acceptable. If you manually type in a page number that's outside of the number of pages we have, the logic returns an empty page. That's, in some sense, accurate. In this scenario the pagination widgets also show links to decrement the page, which implicitly still leads to empty pages. I also consider this fine, mostly because resolving that feels like a per-widget decision. The `ellipsis` widget, for example, still shows a valid last page.

So no, there are no plans to change these behaviors right now. That said, If someone wanted to open a PR that improved the behavior in these cases, I would absolutely review it .

**Closed by pbrisbin** 2018-08-06 15:57 UTC
